/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conectagui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;

/**
 *
 * @author ruan.pablo.a.gomes
 */
public class Cadastro extends javax.swing.JFrame {

    TitledBorder titledBorderNome = BorderFactory.createTitledBorder("Digite seu nome");
    TitledBorder titledBorderEmail = BorderFactory.createTitledBorder("Digite seu e-mail");
    TitledBorder titledBorderSenha = BorderFactory.createTitledBorder("Digite sua senha");

    TitledBorder titledBorderNomeRest = BorderFactory.createTitledBorder("Digite o nome do restaurante");
    TitledBorder titledBorderCNPJ = BorderFactory.createTitledBorder("Digite o CNPJ do restaurante");

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        jCheckBox1Cliente.setSelected(true);
        jTextField1.setBorder(titledBorderNome);
        jTextField2.setBorder(titledBorderEmail);
        jPasswordField1.setBorder(titledBorderSenha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1Cliente = new javax.swing.JCheckBox();
        jCheckBox2Restaurante = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jButton1Cadastrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCheckBox1Cliente.setText("Cliente");
        jCheckBox1Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ClienteActionPerformed(evt);
            }
        });

        jCheckBox2Restaurante.setText("Restaurante");
        jCheckBox2Restaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2RestauranteActionPerformed(evt);
            }
        });

        jButton1Cadastrar.setText("Cadastrar");
        jButton1Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CadastrarActionPerformed(evt);
            }
        });

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox1Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addComponent(jCheckBox2Restaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField2)
                            .addComponent(jPasswordField1)
                            .addComponent(jTextField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButton1Cadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1Cliente)
                    .addComponent(jCheckBox2Restaurante))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1Cadastrar)
                    .addComponent(jButton1))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ClienteActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1Cliente.isSelected()) {
            jCheckBox2Restaurante.setSelected(false);
            jTextField1.setBorder(titledBorderNome);
            jTextField2.setBorder(titledBorderEmail);

        } else {
            jCheckBox2Restaurante.setSelected(true);
            jTextField1.setBorder(titledBorderNomeRest);
            jTextField2.setBorder(titledBorderCNPJ);
        }
    }//GEN-LAST:event_jCheckBox1ClienteActionPerformed

    private void jCheckBox2RestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2RestauranteActionPerformed
        // TODO add your handling code here:
        if (jCheckBox2Restaurante.isSelected()) {
            jCheckBox1Cliente.setSelected(false);
            jTextField1.setBorder(titledBorderNomeRest);
            jTextField2.setBorder(titledBorderCNPJ);
        } else {
            jCheckBox1Cliente.setSelected(true);
            jTextField1.setBorder(titledBorderNome);
            jTextField2.setBorder(titledBorderEmail);
        }
    }//GEN-LAST:event_jCheckBox2RestauranteActionPerformed

    private void jButton1CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CadastrarActionPerformed
        // TODO add your handling code here:
        DAO dao = new DAO();
        String nome = jTextField1.getText();
        String emailOrCnpj = jTextField2.getText();
        String senhaCliente = new String(jPasswordField1.getPassword());

        if (jCheckBox1Cliente.isSelected() == true) {
            CadCliente cliente = new CadCliente(nome, emailOrCnpj, senhaCliente);
            try {
                dao.inserirCliente(cliente);
            } catch (Exception ex) {

            }
        } else {
            CadRestaurante restaurante = new CadRestaurante(nome, emailOrCnpj, senhaCliente);
            try {
                dao.inserirRestaurante(restaurante);
                JOptionPane.showMessageDialog(null, "Cadastro realizado! Aguarde ser aprovado.");
            } catch (Exception ex) {
                
            }
        }
        TelaInicio telaInicio = new TelaInicio();
        telaInicio.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1CadastrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TelaInicio telaInicio = new TelaInicio();
        telaInicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1Cadastrar;
    private javax.swing.JCheckBox jCheckBox1Cliente;
    private javax.swing.JCheckBox jCheckBox2Restaurante;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
