/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conectagui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;

/**
 *
 * @author ruan.pablo.a.gomes
 */
public class Cadastro extends javax.swing.JFrame {

//    TitledBorder titledBorderNome = BorderFactory.createTitledBorder("Digite seu nome");
//    TitledBorder titledBorderEmail = BorderFactory.createTitledBorder("Digite seu e-mail");
//    TitledBorder titledBorderSenha = BorderFactory.createTitledBorder("Digite sua senha");

//    TitledBorder titledBorderNomeRest = BorderFactory.createTitledBorder("Digite o nome do restaurante");
//    TitledBorder titledBorderCNPJ = BorderFactory.createTitledBorder("Digite o CNPJ do restaurante");

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        jCheckBox1Cliente.setSelected(true);
        jLabel3.setVisible(false);
        setResizable(false);

//        jTextField1.setBorder(titledBorderNome);
//        jTextField2.setBorder(titledBorderEmail);
//        jPasswordField1.setBorder(titledBorderSenha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1Cadastrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jCheckBox2Restaurante = new javax.swing.JCheckBox();
        jCheckBox1Cliente = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(476, 513));

        jPanel1.setMinimumSize(new java.awt.Dimension(476, 513));
        jPanel1.setPreferredSize(new java.awt.Dimension(476, 513));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(87, 176, 60));
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 260, -1));

        jTextField2.setBackground(new java.awt.Color(87, 176, 60));
        jTextField2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 260, -1));

        jPasswordField1.setBackground(new java.awt.Color(87, 176, 60));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 260, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruan.pablo.a.gomes\\OneDrive - Accenture\\Desktop\\Faculdade\\7º Semestre\\Front\\projetoA3_Front\\src\\main\\java\\imagens\\tela_cadastro.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(476, 513));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruan.pablo.a.gomes\\OneDrive - Accenture\\Desktop\\Faculdade\\7º Semestre\\Front\\projetoA3_Front\\src\\main\\java\\imagens\\tela_cadastro_rest.png")); // NOI18N
        jLabel3.setText("jLabel1");
        jLabel3.setPreferredSize(new java.awt.Dimension(476, 513));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1Cadastrar.setText("Cadastrar");
        jButton1Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1Cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 150, 40));

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 40));

        jCheckBox2Restaurante.setText("Restaurante");
        jCheckBox2Restaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2RestauranteActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2Restaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, 30));

        jCheckBox1Cliente.setText("Cliente");
        jCheckBox1Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ClienteActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 110, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ClienteActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1Cliente.isSelected()) {
            jCheckBox2Restaurante.setSelected(false);
            jLabel3.setVisible(false);
            jLabel1.setVisible(true);
//          jTextField1.setBorder(titledBorderNome);
//          jTextField2.setBorder(titledBorderEmail);

        } else {
            jCheckBox2Restaurante.setSelected(true);
            jLabel3.setVisible(true);
            jLabel1.setVisible(false);
//            jTextField1.setBorder(titledBorderNomeRest);
//            jTextField2.setBorder(titledBorderCNPJ);
            
        }
    }//GEN-LAST:event_jCheckBox1ClienteActionPerformed

    private void jCheckBox2RestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2RestauranteActionPerformed
        // TODO add your handling code here:
        if (jCheckBox2Restaurante.isSelected()) {
            jCheckBox1Cliente.setSelected(false);
            jLabel1.setVisible(false);
            jLabel3.setVisible(true);

//            jTextField1.setBorder(titledBorderNomeRest);
//            jTextField2.setBorder(titledBorderCNPJ);
        } else {
            jCheckBox1Cliente.setSelected(true);
            jLabel1.setVisible(true);
            jLabel3.setVisible(false);
//            jTextField1.setBorder(titledBorderNome);
//            jTextField2.setBorder(titledBorderEmail);
        }
    }//GEN-LAST:event_jCheckBox2RestauranteActionPerformed

    private void jButton1CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CadastrarActionPerformed
        // TODO add your handling code here:
        DAO dao = new DAO();
        String nome = jTextField1.getText();
        String emailOrCnpj = jTextField2.getText();
        String senhaCliente = new String(jPasswordField1.getPassword());

        if (jCheckBox1Cliente.isSelected() == true) {
            CadCliente cliente = new CadCliente(nome, emailOrCnpj, senhaCliente);
            try {
                dao.inserirCliente(cliente);
            } catch (Exception ex) {

            }
        } else {
            CadRestaurante restaurante = new CadRestaurante(nome, emailOrCnpj, senhaCliente);
            try {
                dao.inserirRestaurante(restaurante);
                JOptionPane.showMessageDialog(null, "Cadastro realizado! Aguarde ser aprovado.");
            } catch (Exception ex) {
                
            }
        }
        TelaInicio telaInicio = new TelaInicio();
        telaInicio.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1CadastrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TelaInicio telaInicio = new TelaInicio();
        telaInicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1Cadastrar;
    private javax.swing.JCheckBox jCheckBox1Cliente;
    private javax.swing.JCheckBox jCheckBox2Restaurante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
