/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conectagui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ruan.pablo.a.gomes
 */
public class ListaRestauranteRest extends javax.swing.JFrame {
    String cnpj;
    /**
     * Creates new form ListaRestauranteRest
     */
    public ListaRestauranteRest(String cnpj) {
        initComponents();
        this.cnpj = cnpj;
        setResizable(false);
        jTextField2cnpjRest.setText(cnpj);
        CadRestaurante[] restaurantes;
        DAO dao = new DAO();
        restaurantes = dao.retornaListaRestaurantesCadastrados();
        for(int index = 0; index != restaurantes.length; index++){
            if(restaurantes[index].getCnpjRestaurante().equals(cnpj)){
                jTextField1nomeRest.setText(restaurantes[index].getNomeRestaurante());
                jTextField3notaRest.setText(Integer.toString(restaurantes[index].getNota()));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1nomeRest = new javax.swing.JTextField();
        jTextField2cnpjRest = new javax.swing.JTextField();
        jTextField3notaRest = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1atualizar = new javax.swing.JButton();
        jButton2deletar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(476, 513));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1nomeRest.setBackground(new java.awt.Color(87, 176, 60));
        jTextField1nomeRest.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField1nomeRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1nomeRestActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1nomeRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 135, 260, -1));

        jTextField2cnpjRest.setEditable(false);
        jTextField2cnpjRest.setBackground(new java.awt.Color(87, 176, 60));
        jTextField2cnpjRest.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField2cnpjRest.setDisabledTextColor(new java.awt.Color(87, 176, 60));
        jPanel1.add(jTextField2cnpjRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 205, 260, 20));

        jTextField3notaRest.setEditable(false);
        jTextField3notaRest.setBackground(new java.awt.Color(87, 176, 60));
        jTextField3notaRest.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        jTextField3notaRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3notaRestActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3notaRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 297, 260, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruan.pablo.a.gomes\\OneDrive - Accenture\\Desktop\\Faculdade\\7º Semestre\\Front\\projetoA3_Front\\src\\main\\java\\imagens\\rest_meu_restaurante.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 520));

        jButton1atualizar.setText("Atualizar");
        jButton1atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1atualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 373, 160, 30));

        jButton2deletar.setText("Deletar");
        jButton2deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2deletarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2deletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 373, 160, 30));

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1nomeRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1nomeRestActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1nomeRestActionPerformed

    private void jTextField3notaRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3notaRestActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField3notaRestActionPerformed

    private void jButton1atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1atualizarActionPerformed
        // TODO add your handling code here:
        
        String nomeRestaurante = jTextField1nomeRest.getText();
        String cnpjRestaurante = jTextField2cnpjRest.getText();
        int notaRestaurante = Integer.parseInt(jTextField3notaRest.getText());
        
        CadRestaurante restaurante = new CadRestaurante (nomeRestaurante, cnpjRestaurante, notaRestaurante); 
 
        DAO dao = new DAO();
        try {
            dao.atualizarRestaurante(restaurante);
            JOptionPane.showMessageDialog(null, "Atualização realizada!");

        } catch (Exception ex) {
        
        }
        
        GerenciamentoRestaurantes telaGerRest = new GerenciamentoRestaurantes(cnpj);
        telaGerRest.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1atualizarActionPerformed

    private void jButton2deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2deletarActionPerformed
        // TODO add your handling code here:
        String cnpjRestaurante = jTextField2cnpjRest.getText();
        
        CadRestaurante restaurante = new CadRestaurante (cnpjRestaurante); 
        DAO dao = new DAO();
        try{
            dao.deletarRestaurante(restaurante);
            JOptionPane.showMessageDialog(null, "Deleção realizada!");
        }catch(Exception e){
            
        }
        GerenciamentoRestaurantes telaGerRest = new GerenciamentoRestaurantes(cnpj);
        telaGerRest.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2deletarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GerenciamentoRestaurantes gerRest = new GerenciamentoRestaurantes(cnpj);
        gerRest.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaRestauranteRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaRestauranteRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaRestauranteRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaRestauranteRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaRestauranteRest("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1atualizar;
    private javax.swing.JButton jButton2deletar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1nomeRest;
    private javax.swing.JTextField jTextField2cnpjRest;
    private javax.swing.JTextField jTextField3notaRest;
    // End of variables declaration//GEN-END:variables
}
