/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conectagui;

import static java.awt.Color.BLACK;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author ruan.pablo.a.gomes
 */
public class ListaCuponsCliente extends javax.swing.JFrame {
    String login;
    /**
     * Creates new form ListaCuponsCliente
     */
    public ListaCuponsCliente(String login) {
        initComponents();
        this.login = login;
        setResizable(false);
        DAO dao = new DAO();
        List<String> x = dao.retornaCuponsCliente(login);
        
        JLabel[] labels = new JLabel[5];
        labels[0] = cupom1;
        labels[1] = cupom2;
        labels[2] = cupom3;
        labels[3] = cupom4;
        labels[4] = cupom5;

        for(int i = 0; i != x.size(); i++){
            if(labels[i].getText().isEmpty()){
                labels[i].setText(x.get(i));
            }
        }
        
//        if (x.size() != 0) {
//            for (int i = 0; i != x.size(); i++) {
//                if (i == 0) {
//                    jTextArea1listaCupons.setText("");
//                }
//                jTextArea1listaCupons.append("\nCupom " + (i + 1) + ": " + x.get(i) + "\n\n");
//            }
//        }else{
//            jTextArea1listaCupons.setText("Poxa, você não possui cupons! \nQue tal frequentar e avaliar mais restaurantes da nossa lista?");
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cupom1 = new javax.swing.JLabel();
        cupom2 = new javax.swing.JLabel();
        cupom3 = new javax.swing.JLabel();
        cupom4 = new javax.swing.JLabel();
        cupom5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(476, 513));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(cupom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 190, 20));
        jPanel1.add(cupom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 116, 190, 20));
        jPanel1.add(cupom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 190, 20));
        jPanel1.add(cupom4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 226, 190, 20));
        jPanel1.add(cupom5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 190, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruan.pablo.a.gomes\\OneDrive - Accenture\\Desktop\\Faculdade\\7º Semestre\\Front\\projetoA3_Front\\src\\main\\java\\imagens\\cliente_tela_cupom.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 480, 520));

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GerenciamentoCliente gerCliente = new GerenciamentoCliente(login);
        gerCliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaCuponsCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaCuponsCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaCuponsCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaCuponsCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaCuponsCliente("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cupom1;
    private javax.swing.JLabel cupom2;
    private javax.swing.JLabel cupom3;
    private javax.swing.JLabel cupom4;
    private javax.swing.JLabel cupom5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
